### ISSUE TITLE
CentOS 5 & 6 Installation Instructions Need Updating

### ISSUE THREAD

**Issue by williamdean** [cluther/snmposter#6]
Twisted was updated on PyP to Twisted 15.5.0, which requires Python 2.7.

```
(snmposter)[root@localhost ~]# pip install snmposter
Downloading/unpacking snmposter

  Downloading snmposter-1.0.3.tar.gz
  Running setup.py egg_info for package snmposter
Downloading/unpacking Twisted (from snmposter)
  Downloading Twisted-15.5.0.tar.bz2 (3.1MB): 3.1MB downloaded
  Running setup.py egg_info for package Twisted
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/snmposter/build/Twisted/setup.py", line 64, in <module>
        main(sys.argv[1:])
      File "/snmposter/build/Twisted/setup.py", line 45, in main
        from twisted.python.dist import (
      File "./twisted/__init__.py", line 55, in <module>
        _checkRequirements()
      File "./twisted/__init__.py", line 17, in _checkRequirements
        raise ImportError("Twisted requires Python 2.7 or later.")
    ImportError: Twisted requires Python 2.7 or later.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/snmposter/build/Twisted/setup.py", line 64, in <module>

    main(sys.argv[1:])

  File "/snmposter/build/Twisted/setup.py", line 45, in main

    from twisted.python.dist import (

  File "./twisted/__init__.py", line 55, in <module>

    _checkRequirements()

  File "./twisted/__init__.py", line 17, in _checkRequirements

    raise ImportError("Twisted requires Python 2.7 or later.")

ImportError: Twisted requires Python 2.7 or later.

```

The instructions for Cent5/6 should be updated to install an older version of Twisted prior to installing snmposter via pip.

```
wget http://twistedmatrix.com/Releases/Twisted/13.2/Twisted-13.2.0.tar.bz2
bzip2 -d Twisted-13.2.0.tar.bz2
tar -xvf Twisted-13.2.0.tar
cd Twisted-13.2.0
python setup.py install
cd ..
```

**Comment by dougsyer** [comment]
tks for the heads up...
